### ISSUE TITLE
Creating a CI Workflow to Check for Broken Links

### ISSUE THREAD

**Issue by tkwbr999** [tKwbr999/personal-telling-service#4]
## Requirements
- Must be triggered via GitHub Workflows
- Should report errors when broken links are detected
- Must generate a report identifying which specific resources have broken links

## Enhanced Prompt

```yaml
name: Check for Broken Links

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight

jobs:
  check-links:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install link checker
      run: npm install -g broken-link-checker
      
    - name: Check for broken links
      id: link-check
      run: |
        # Create output directory
        mkdir -p ./link-check-results
        
        # Run link checker and output results to a file
        # Adjust the URL to your site or documentation
        blc https://your-site-or-docs-url.com -ro --filter-level 3 > ./link-check-results/broken-links.txt
        
        # Check if there are broken links and set output variable
        if grep -q "BROKEN" ./link-check-results/broken-links.txt; then
          echo "broken_links=true" >> $GITHUB_OUTPUT
          echo "::error::Broken links detected! See the report for details."
        else
          echo "broken_links=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Generate broken links report
      if: steps.link-check.outputs.broken_links == 'true'
      run: |
        echo "## Broken Links Report" > ./link-check-results/report.md
        echo "" >> ./link-check-results/report.md
        echo "The following broken links were detected:" >> ./link-check-results/report.md
        echo "" >> ./link-check-results/report.md
        grep "BROKEN" ./link-check-results/broken-links.txt | awk '{print "- " $0}' >> ./link-check-results/report.md
      
    - name: Upload broken links report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: broken-links-report
        path: ./link-check-results/
        
    - name: Fail if broken links detected
      if: steps.link-check.outputs.broken_links == 'true'
      run: exit 1
```

## Usage Instructions

1. Create a `.github/workflows` directory in your repository if it doesn't exist.
2. Add a new file (e.g., `check-links.yml`) in that directory with the contents above.
3. Customize the URL in the `blc https://your-site-or-docs-url.com` line to point to your site.
4. Adjust the branch names and cron schedule as needed.
5. For repository-specific content (like Markdown files), you may need to modify the script to crawl local files instead.

## Alternative Tools

You could also consider these alternatives:
- lychee: A fast, async link checker
- markdown-link-check: Specifically for checking Markdown files
- muffet: A fast website link checker

Remember to customize the workflow to your specific needs, especially regarding which directories or file types should be checked.
