### ISSUE TITLE
Creating a CI Workflow to Detect Project Build Errors

### ISSUE THREAD

**Issue by tkwbr999** [tKwbr999/personal-telling-service#5]
## GitHub Workflow for CI Checks

```yaml
name: Project Build Checker

on:
  push:
    branches: [ main, master, development ]
  pull_request:
    branches: [ main, master, development ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      id: install
      run: |
        npm ci
      continue-on-error: true
      
    - name: Check for dependency installation errors
      if: steps.install.outcome == 'failure'
      run: |
        echo "::error::Dependency installation failed"
        npm ci --verbose > dependency-error.log 2>&1
        echo "## Dependency Installation Error" > error-report.md
        echo "\`\`\`" >> error-report.md
        cat dependency-error.log >> error-report.md
        echo "\`\`\`" >> error-report.md
        exit 1
        
    - name: Analyze package.json
      id: analyze
      run: |
        echo "## Package.json Analysis" > package-analysis.md
        echo "### Project Dependencies:" >> package-analysis.md
        jq '.dependencies' package.json >> package-analysis.md
        echo "### Dev Dependencies:" >> package-analysis.md
        jq '.devDependencies' package.json >> package-analysis.md
        echo "### Scripts:" >> package-analysis.md
        jq '.scripts' package.json >> package-analysis.md
        
    - name: Run build
      id: build
      run: |
        npm run build
      continue-on-error: true
      
    - name: Report build errors
      if: steps.build.outcome == 'failure'
      run: |
        echo "::error::Build failed! See the error report for details."
        npm run build --verbose > build-error.log 2>&1
        echo "## Build Error Report" > error-report.md
        echo "\`\`\`" >> error-report.md
        cat build-error.log >> error-report.md
        echo "\`\`\`" >> error-report.md
        
    - name: Upload error report
      if: steps.install.outcome == 'failure' || steps.build.outcome == 'failure'
      uses: actions/upload-artifact@v3
      with:
        name: error-report
        path: |
          error-report.md
          package-analysis.md
          
    - name: Fail workflow if build failed
      if: steps.build.outcome == 'failure'
      run: exit 1
```

## Makefile for Local Build Error Detection

```makefile
.PHONY: check-build check-dependencies analyze-package full-check clean

# Default target
help:
	@echo "Available commands:"
	@echo "  make check-build         - Check for build errors"
	@echo "  make check-dependencies  - Check for dependency issues"
	@echo "  make analyze-package     - Analyze package.json"
	@echo "  make full-check          - Run all checks"
	@echo "  make clean               - Remove log files"

# Check for build errors
check-build:
	@echo "Checking for build errors..."
	@npm run build > build.log 2>&1 || (echo "⛔ Build failed! See build.log for details"; cat build.log | grep -i "error"; exit 1)
	@echo "✅ Build successful!"

# Check for dependency issues
check-dependencies:
	@echo "Checking dependencies..."
	@npm ci > dependencies.log 2>&1 || (echo "⛔ Dependency installation failed! See dependencies.log for details"; cat dependencies.log | grep -i "error"; exit 1)
	@echo "✅ Dependencies installed successfully!"

# Analyze package.json
analyze-package:
	@echo "Analyzing package.json..."
	@if [ ! -f package.json ]; then echo "⛔ package.json not found!"; exit 1; fi
	@echo "📦 Project dependencies:"
	@cat package.json | grep -A 100 '"dependencies"' | grep -B 100 '"devDependencies"' | grep -v '"devDependencies"'
	@echo "🔧 Dev dependencies:"
	@cat package.json | grep -A 100 '"devDependencies"' | grep -B 100 -e '"scripts"' -e '$$' | grep -v '"scripts"'
	@echo "🚀 Scripts:"
	@cat package.json | grep -A 100 '"scripts"' | grep -B 100 -e '"dependencies"' -e '"devDependencies"' -e '$$' | grep -v '"dependencies"' | grep -v '"devDependencies"'
	@echo "✅ Analysis complete!"

# Run all checks
full-check: check-dependencies analyze-package check-build
	@echo "🎉 All checks passed successfully!"

# Clean log files
clean:
	@rm -f build.log dependencies.log
	@echo "🧹 Logs cleaned!"
```

### GitHub Workflow:
1. Create a `.github/workflows` directory in your repository if it doesn't exist
2. Create a new file (e.g., `build-checker.yml`) in that directory with the GitHub workflow content
3. Customize branch names and build commands based on your project needs
4. Push the changes to trigger the workflow

### Makefile:
1. Place the Makefile in the root of your project
2. Run `make help` to see available commands
3. Run `make full-check` to perform all checks
4. Check output logs for detailed error information

### Additional Customization:
- Adjust the Node.js version in the workflow as needed
- Modify build commands if your project uses a different build system
- Add additional checks for linting, testing, etc.
- For non-Node.js projects, replace npm commands with appropriate build tools

The GitHub workflow will automatically run on pushes and pull requests, while the Makefile provides a convenient way to perform checks locally before committing changes.
